name: plantiful
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  pretty_dio_logger: ^1.3.1
  flutter_bloc: ^8.1.4
  bloc: ^8.1.3
  dio: ^5.4.1
  percent_indicator: ^4.2.3
  google_fonts: ^6.2.1
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
