name: plantiful
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  pretty_dio_logger: ^1.3.1
  flutter_bloc: ^8.1.4
  bloc: ^8.1.3
  dio: ^5.4.1
  percent_indicator: ^4.2.3
  google_fonts: ^6.2.1
  geolocator: ^12.0.0
  weather: ^3.1.1
  transparent_image: ^2.0.1
  firebase_auth: ^5.2.0
  atlas_icons: ^0.0.12
  intl: ^0.19.0
  shared_preferences: 
  page_view_dot_indicator: ^2.1.0
  firebase_core: ^3.4.0
  flutter_animate: ^4.5.0
  cloud_firestore: ^5.4.0
  flutter_svg: ^2.0.10+1
  flutter_local_notifications: ^17.2.3
  loading_animation_widget: ^1.3.0
  workmanager: ^0.5.2
  flutter_expandable_fab: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/location.svg
    - assets/gardening.svg
    - assets/welcome.svg
    - assets/notification.svg
    - assets/health.svg
 
